parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    TCGdex\TCGdex:
        factory: ['App\Service\Licence\Pokemon\TcgdexFactory', 'create']
